Work around snd_pcm_poll_descriptors argument check issue
MPD does not work properly with bluez-alsa driven Bluetooth devices, at
least not in certain configurations. In those it emits the following
error:

  > output: Failed to play on "XXX" (alsa): snd_pcm_poll_descriptors() failed: Invalid argument
  > exception: Failed to open audio output

The reason seems to be that MPD makes certain assumptions about some
poll file descriptor array that bluez-alsa receives (though ALSA
callbacks) but disagrees with. The alsa-lib API supposedly has the
contract under specified.

If you feel like having a bit more life juice drained out of you, you
are encouraged to read up on the circus here:
https://github.com/Arkq/bluez-alsa/issues/174
https://github.com/MusicPlayerDaemon/MPD/issues/432
https://github.com/MusicPlayerDaemon/MPD/issues/548
https://github.com/MusicPlayerDaemon/MPD/issues/1037
https://github.com/MusicPlayerDaemon/MPD/issues/1204

This change works around the issue by ignoring the return value of
the call to bluealsa_dbus_connection_poll_fds from within
bluealsa_poll_descriptors, which is the PCM devices poll_descriptors
handler. Better than no sound...